### ISSUE TITLE
请问能否也把我们的工作放到您的 list 中？

### ISSUE THREAD

**Issue by SupritYoung** [luban-agi/Awesome-Domain-LLM#2]
你好！对您重要的收集工作表示由衷的赞赏！我是 Zhongjing-LLaMA 医疗开源大模型的作者，我们的模型也取得了一定的影响力，请问可以麻烦您可以也放入 list 中嘛：https://github.com/SupritYoung/Zhongjing

**Comment by wuyifan18** [comment]
好的，感谢您对本工作的认可！
