### ISSUE TITLE
最近还有更新吗？

### ISSUE THREAD

**Issue by Liusuthu** [luban-agi/Awesome-Domain-LLM#3]
我看上一次更新是去年的十一月份了，请问是否有新的调研数据？

**Comment by wuyifan18** [comment]
精力有限，目前没有最新的调研数据。如果你有相关调研，欢迎提交PR~

**Comment by Liusuthu** [comment]
https://github.com/lonePatient/awesome-pretrained-chinese-nlp-models

这个仓库里有很多最新的数据，最新一次更新是6.1附近，你可以查看一下
